### ISSUE TITLE
Code Editor 2: [Feather] Critical: Exception Message: Index was outside the bounds of the array when hovering built-in constant

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#10301]
### Description

I notice this error message in the ui.log when I first loaded my project. However, it appears to constantly populate the ui.log when I am in Code Editor 2. The one constant I was hovering around was 'image_angle'.

This is very inconsistent, it happens when I am hovering over pretty much anything that should return some form of tooltip, but if I have multiple references to say obj_block, then it errors when hovering on some of the refs but not others.

```
[12:26:37:551(8342)] [GMLServer] Critical: Failed to handle request textDocument/hover 69
[12:26:37:557(8342)] [GMLServer] Critical: Exception Message: Index was outside the bounds of the array.
Stack Trace:
 at Feather.Logic.Utility.DocumentUtility.GetExpressionAtPosition(String scriptContents, Int32 lineIndex, Int32 column, String& word, Char& triggerCharacter, Int32& offset)
 at OddlySpecific.Feather.ResourceContext.GetExpressionAtPosition(Int32 lineIndex, Int32 column, String& word, Char& triggerCharacter, Int32& offset)
 at GameMakerLanguageServer.Handlers.HoverHandler.Handle(HoverParams request, CancellationToken cancellationToken)
 at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
 at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
 at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()

[12:26:44:898(8342)] [GMLServer] Critical: Failed to handle request textDocument/hover 70
[12:26:44:901(8342)] [GMLServer] Critical: Exception Message: Index was outside the bounds of the array.
Stack Trace:
 at Feather.Logic.Utility.DocumentUtility.GetExpressionAtPosition(String scriptContents, Int32 lineIndex, Int32 column, String& word, Char& triggerCharacter, Int32& offset)
 at OddlySpecific.Feather.ResourceContext.GetExpressionAtPosition(Int32 lineIndex, Int32 column, String& word, Char& triggerCharacter, Int32& offset)
 at GameMakerLanguageServer.Handlers.HoverHandler.Handle(HoverParams request, CancellationToken cancellationToken)
 at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
 at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
 at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
```

### Steps To Reproduce

The repo steps are accurate, however the issue can be a little hard to repo as sometimes the issue happens all the time and other times it just works fines. This has been tested on multiple projects and the issue happens on all of them.

Issue does happen on this attached project, you may need to hover over some built-in constants for a while before it raises it's ugly face.
[Test Project.zip](https://github.com/user-attachments/files/19776083/Test.Project.zip)
 
1. Start GameMaker
2. Create project and add an object
3. Add some built-in constants
4. Hover over them
5. See the issue

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2024.1300 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

**Comment by scott-dunbar** [comment]
I was also able to repro this issue the following way

1. Open attached project
2. Open an object1
3. Hover over the functions in the events
4. Check UI.log

**Comment by YYDan** [comment]
Several others in QA have realised they have this in their ui.logs also; however, 100% steps have not always been found for our projects.

**Comment by zreedy** [comment]
Fixed. The reproduction requires a comment at the beginning of the previous line with no leading whitespace on the either line.

**Comment by sihammill** [comment]
Hovering over a built-in constant with a comment directly above it with no space still cause the issue.

```
// hello
gravity = 0.5;
```

However adding a space between the comment and the constant resolves the issue

```
// hello

gravity = 0.5;
```

**Comment by sihammill** [comment]
Fix appears to be sorted in Beta IDE v2024.1400.0.800  Runtime v2024.1400.0.806

**Comment by Emc1923** [comment]
I'm still seeing the issue with the attached project: https://api.gamemaker.io/api/github/downloads/2801dce9-ac2c-443a-9ee6-e41c48935cf8

To reproduce:
1. Open obj_player
2. Rename a random obj_ (for example obj_collision) while the object is also open
3. Go to a collision event inside obj_player
4. Change the collision obj to the renamed object (obj_collision_renamed)
5.  Observe the functions in the event are greyed out
6. Attempt to open a function in the manual
7. See the message in the ui.log
