### ISSUE TITLE
Room Editor: Shortcut keys for tileset editing do not work properly in 2023.11

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#2365]
### Description
Whenever I try to put something then change to I dunno grid on off or pencil tool, it just wont or I have to click to screen to activate even though I was clicking... it is bizzare

### Steps To Reproduce
*Room editor
*Try to use a tileset
*Use tileset shortcuts or any room shortcut key
*Observe

[0d34571b-7661-471e-a78e-e6a176fca0f1](https://api.gamemaker.io/api/github/downloads/0d34571b-7661-471e-a78e-e6a176fca0f1)

**Comment by adketuri** [comment]
Also running into this, it looks like for the hotkeys to activate, you have to click on the room itself somewhere first.

This means selecting a tile from the room editor results in the room hotkeys (S, D, F, etc) no longer functioning.

I also have to click on the room first to paste new instances. If you just copy from one room, select another room's instance layer, and try to paste, nothing happens. This was a bit confusing for me at first. It would be great if the room hotkeys worked even when selecting layers or the room editor. (I find the layer hotkeys less useful/rarely used.)

**Comment by SmithTom6304** [comment]
Fixed - tile layer shortcuts are "gadget" shortcuts, and so when registered with the shortcut manager were only being checked when the gadget had focus.
I've updated this so that these shortcuts are now being handled by the RoomEditor itself, which will check it's active tool (ie. Tile Layer) shortcuts before checking it's module-level shortcuts. This means that these tool shortcuts are now checked no matter what section of the RoomEditor has focus.
This also fixes the issues with Copy/Pasting of instances (and others), as these shortcuts were technically gadget shortcuts registered with the Room Edit Area, which was losing focus when selecting a new layer. These are now module shortcuts.

**Comment by SmithTom6304** [comment]
Fix has had some unintended consequences (RoomEditorModule is now taking priority over other hotkeys, like Delete and Rename). Changes have been reverted, so re-opening this.

**Comment by SmithTom6304** [comment]
Additional fix has gone in - RoomEditor shortcuts now only execute after the KBSM execution step _if_ no other shortcuts were executed, and only if the RoomEditor has focus.
We have some work going in for 2024.04 that improves on this, but we want this fix in for 2024.02 and so a temporary solution has gone in. Because of this, this will likely need re-tested for 2024.04.

**Comment by alicemoretti** [comment]
This issue still appears for me on Beta IDE v2024.200.0.499 Beta Runtime v2024.200.0.516. 

Room's hotkey are not executed when the Tile layer is selected. Reopening the bug. Thank you.

**Comment by caitlinrmcintyre** [comment]
Still experiencing this issue, here are my repo steps:
1. Go into rm_level_1 and into the CollisionTiles layer.
2. Place a tile on the map and press G, notice how the grid doesn't toggle on or off.
3. Click on the grid button in the toolbar and then press G and notice the grid now toggles.

**Comment by SmithTom6304** [comment]
For any users coming by this - this is _mostly_ fixed for 2024.02, but we still have some straggling issues relating to the zooming / grid toggling shortcuts which will be going in for 2024.04 instead.

**Comment by SmithTom6304** [comment]
Remaining zoom widget shortcut issues should now be fixed.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.800.0.603  Runtime v2024.800.0.625. 

Thank you.
