### ISSUE TITLE
Performance: [Mac IDE] Stutters & increases RAM usage over extended sessions of editing projects

### ISSUE THREAD

**Issue by NanoSharkGames** [YoYoGames/GameMaker-Bugs#4424]
### Description
After editing code & compiling a project on the Mac IDE of GameMaker for about a couple hours, the IDE stutters & RAM usage increased from half a GB to more than 3 GB. This was tested on IDE version 2023.11.1.

### Steps To Reproduce
1. Open GameMaker
2. Load project whose folder is about ~16MB according to Finder / Get Info.
3. Edit code & compile project for a couple hours without closing.
4. Notice stutters in editing code & RAM usage ramping up significantly, according to Activity Monitor.

[244c3515-f6a6-405e-84d8-9742faabcfd2](https://api.gamemaker.io/api/github/downloads/244c3515-f6a6-405e-84d8-9742faabcfd2)

**Comment by Retrific** [comment]
Maybe related: https://github.com/YoYoGames/GameMaker-Bugs/issues/2528

**Comment by NanoSharkGames** [comment]
I am using version 2024.2 and the issue is apparent after using it for a couple of hours. The color wheel icon on Mac shows up more often & slows down my workflow.

<img width="999" alt="Screenshot 2024-04-09 at 3 18 25 PM" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/40772036/f28379f0-4828-49d1-9377-2e03aeffd898">

**Comment by stuckie** [comment]
Oh.. thats an interesting amount of ports open.. I wonder if that is pointing towards a thread leak.

Will have a look into this a bit more in the morning, thanks!

**Comment by NanoSharkGames** [comment]
Any updates on the investigation into the port/thread leaks?

**Comment by stuckie** [comment]
Much like the related issue above, this is proving to be a menace to pin down. From a quick look that I had the other week, nothing immediately stood out; so again it'll likely be some sort of interaction between systems where artificially poking about isn't going to cut it.

As the April release is getting closer to the end, there should be a bit of time to sit down and use the IDE with some purpose - going through some tutorials, for instance - with all the profiling tools hooked up. That's the plan anyway, and hopefully that highlights something.

I'm honestly looking forward to the probable dumb fix that this is going to be at the end, after it's eluded us for so long.

**Comment by NanoSharkGames** [comment]
Maybe related to this issue: I do notice that my MacBook's battery drains significantly when using the IDE compared to other software, especially for an extended period of time. Do you suspect that the reason is because of this issue? Also, are there any optimizations planned for making the IDE more lightweight?

Thanks so much for the helpful responses, & I hope you have a good rest of your week.

**Comment by NanoSharkGames** [comment]
I just updated to 2024.2 & the issue has not improved for me.

I took two Activity Monitor screenshots, one CPU & one memory usage, which was around the same minute. I used the IDE for only 30 minutes before I took these screenshots.

![GM CPU Usage 2024-05-02 4 25 34 PM](https://github.com/YoYoGames/GameMaker-Bugs/assets/40772036/81a73b34-b5fb-4baa-add3-9e601d481df8)
![GM Mem Usage 2024-05-02 4 25 50 PM](https://github.com/YoYoGames/GameMaker-Bugs/assets/40772036/d98543af-c971-480a-85c2-f7f5c0afecf0)

**Comment by NanoSharkGames** [comment]
I downloaded & tested the 2024.4.1 hotfix, which promises to fix this issue. The memory usage still increases over time, but not as rapidly.

**Comment by thennothinghappened** [comment]
I'm just popping in here on Russell's advice to do so - I _feel_ like one of the big leaks could be related to saving. I have a strong habit of saving over and over on the order of seconds while I type - a bad habit I've picked up from how often my power goes out. Over about an hour's time it feels on MacOS (I also do this on Windows without issue) that it gradually gets slower and stutterier. Checking Activity Monitory I then see the IDE has climbed gigabytes in usage.

This observation may be a red herring for this, but did also briefly check the memory usage while the IDE saved, and each time it did it it seemed to be trending upward.

**Comment by NanoSharkGames** [comment]
After more testing with the 2024.4.1 Mac IDE on my MacBook Pro, there are still memory leaks & increased resource usage over time. This issue, in addition to the ProMotion IDE frame rate bug I filed, makes the IDE slower over time & causes more battery drain & heat.

**Comment by Emc1923** [comment]
Performance issues still present in Betas 2024.6, tested as of  IDE v2024.600.0.572 Beta Runtime v2024.600.0.597.

**Comment by stuckie** [comment]
For those wondering, we found some thread logic that was misbehaving.. it worked better on the machines I tested, but, like most of these issues have been, it seems like it's not worked for every configuration. It will be in the next beta, so hopefully it helps some others.

**Comment by NanoSharkGames** [comment]
While performance & RAM usage over time has improved with the latest betas, RAM still ramps up slightly over time.

**Comment by NanoSharkGames** [comment]
Might be unrelated to this specific issue, but wanted to point out the following anyway: I am observing a significant improvement in performance & battery life on my M2 MacBook Pro while using the IDE & testing projects. Currently using 2024.6.2.

**Comment by NanoSharkGames** [comment]
I filed a new bug report relating to this issue to submit a new UI.log for more information into this issue:

#7435

**Comment by YYDan** [comment]
You could have just added your ui.log here ;)

**Comment by NanoSharkGames** [comment]
I am still noticing higher RAM usage & lags/stutters on 2024.8.1. Are there any updates regarding this issue that the team can share?

**Comment by stuckie** [comment]
In the 2024.1100/November betas, there is a rework over how we handle some callbacks internally within the IDE which will hopefully help this.. we're still pulling things apart to get a better look as to what this could be though; once things are in smaller pieces, it's easier to test against rather than a large monolithic blob!

**Comment by stuckie** [comment]
We have committed many more performance fixes in the current beta, if you are able to verify this helps.

I'm going to close this just now, but if this has not made any appreciable difference, please let us know!

**Comment by NanoSharkGames** [comment]
After using the latest monthly IDE version for a couple hours, I still notice stutters in typing code & memory usage continues to go up. Hopefully the privately attached information will help investigate this further. I also reduced the undo redo stack & the issue still persists.

<img width="1000" alt="Image" src="https://github.com/user-attachments/assets/c148a4a2-71ad-454c-8848-d9eba43254b1" />


[7fcfc694-555a-40df-9905-35bfbf6ba28f](https://api.gamemaker.io/api/github/downloads/7fcfc694-555a-40df-9905-35bfbf6ba28f)
