### ISSUE TITLE
Shadowed array access in function call

### ISSUE THREAD

**Issue by HannulaTero** [YoYoGames/GameMaker-Bugs#4489]
### Description
In function call, if local variable shadows instance variable, you still can access and assign instance variable by using "self.variable". But this doesn't work if you also access array in the variable like "self.array[0] = array[1];". 

Previous example acts like "array[0] = array[1]", which will assign value in local variable instead of instance variable. I have determined this to be case when Copy on Write behaviour is disabled, and using accessor [@ doesn't affect it. Assignment seems to be work correctly when using accessor while Copy on Write is enabled. 

This problem also appears when using constructors, like: 
```
function Struct(array) constructor {
    self.array = [0, 0, 0];
    self.array[0] = array[0];
    self.array[1] = array[1];
    self.array[2] = array[2];
}
var struct = new Struct([10, 20, 30]);
```

### Steps To Reproduce
1) Copy on write is disabled.
2) Store array reference in instance variable.
3) Make function which takes array reference as parameter.
4) Parameter has same name as instance variable.
5) Modify instance with local: "self.array[0] = array[0] + 5;".
6) This modifies array in local variable, not instance.

[c62b4acc-4b88-49b2-ab2f-728b2201717c](https://api.gamemaker.io/api/github/downloads/c62b4acc-4b88-49b2-ab2f-728b2201717c)

**Comment by rwkay** [comment]
When I run this on my local build of the current Beta I get this...
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/3646448/efe0a39e-1a44-49ea-ab27-1c71d330b9d1)
I think this means everything is working OK - I have fixed a few issues over the last few days which may account for this

**Comment by HannulaTero** [comment]
Good to hear! In your image all seems to be ok and working correctly. For reference, here is what I got:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/73119568/c6fd41bd-af94-47ac-b877-2e5e32a51050)
So I would say the issue has been resolved :) 
Of course in the next beta I can run the project to see whether issue persist on my machine.
