### ISSUE TITLE
"Z-Tilt" Shader Not Working in Runtime

### ISSUE THREAD

**Issue by garlitzj** [YoYoGames/GameMaker-Bugs#5804]
### Description

I have been using code and shaders adapted from this blog post for years without issue: https://gamemaker.io/en/blog/z-tilting-shader-based-2-dot-5d-depth-sorting. However, I recently updated my IDE to the latest version (137) and Runtime v2024.4.0.168, and now the Z-Tilt functionality has completely stopped working (I had last done an IDE/runtime update in late Feb). I am somewhat sure that this same issue doesn't occur on the Mac version of GMS, but don't have my Mac handy to confirm.

I know this is a super specific issue, but this was 100% working prior to the update. Even opening the blog post's sample file as a new project is now broken. Rather than attaching my current project, where this functionality is only in very specific places, I have referenced the Z-Tilt sample repo from which the code was adapted.

### Steps To Reproduce

See sample code here: https://github.com/GameMakerDiscord/z-tilting

Observe the shader is not working as intended (depth sorting and billboarding seems off).

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by JonnoRobson** [comment]
The April 2024 release contains a change which means that vertex corner IDs are now applied when drawing tilemaps if enabled. The "z-tilt" shader uses vertex corner IDs to apply a z offset to the top vertices when drawing, meaning that the recent change meant a z offset was applied to tile map squares as well as all the desired sprites. I've merged a pull request into the "z-tilting" project repository which changes the "render_layer_master" script and "obj_render" Create event so that vertex corner IDs are disabled when drawing the tile maps. If you're using that project then getting the latest version should fix the issues with depth sorting, alternatively you can implement the changes in your own project if you've adapted it for your own purposes.

**Comment by SirSwagalot** [comment]
This bug is still ongoing, after downloading and installing the latest Z-tilt build and running the game, this error appears: 

Variable <unknown_object>.render_layer_tilemap(100017, -2147483648) not set before reading it.
 at gml_Object_obj_render_Create_0 (line 28) - layer_script_end(layer_get_id("blyr"),render_layer_tilemap) // start zbuffering after background has drawn and cleared the screen!
############################################################################################
gml_Object_obj_render_Create_0 (line 28)

We are having the same problem and still unsure how to fix this. Seems like we will just have to revert to the previous version of gamemaker until there is an update. Any help is greatly appreciated.
