### ISSUE TITLE
Code Editor 2: Code in newly created objects will not be colored or analyzed by feather until the project is restarted

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5948]
### Description
If you create a brand new object and add an event to it, any code you type into that object won't get colored or have any feather underlines. This will continue being true until the project is restarted.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6a8e1b25-d365-44a1-bb9e-85d452ce3e06

### Steps To Reproduce
While CE2 is enabled, create a new object and add a new event to it. Any code you type in that event will not recieve any syntax highlighting or errors until the project is reloaded.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[26dacf83-137c-4ac3-bd5e-23bdda67ec60](https://api.gamemaker.io/api/github/downloads/26dacf83-137c-4ac3-bd5e-23bdda67ec60)

**Comment by zreedy** [comment]
Fixed. There were 2 issues here, first was a regression relating to https://github.com/YoYoGames/GameMaker-Bugs/issues/5257
The second is a platform specific issue observed on Mac OS X and Linux. OmniSharp mangles the deserialization of URIs from the `DidCreateFileHandler` and `DidDeleteFileHandler` API endpoints (an oddity as everything else uses the migratory `DocumentUri` class instead of the .NET native `Uri` class). In short, the mangled URI resulted in an exception on the Server preventing the creation of the context which performs Language Services. It's unclear if this is a bug in .NET or in OmniSharp. However a workaround as been written to deal with mangled URIs.

**Comment by mgeddesGM** [comment]
verified in  IDE v2024.600.0.578  Runtime v2024.600.0.604

**Comment by mgeddesGM** [comment]
can be verified once tested on mac

**Comment by Emc1923** [comment]
On mac is blocked by https://github.com/YoYoGames/GameMaker-Bugs/issues/5418

**Comment by caitlinrmcintyre** [comment]
Reopening as I'm still seeing the issue on Windows in IDE v2024.600.0.579  Runtime v2024.600.0.605

**Comment by zreedy** [comment]
This should have been fixed by other now closed tickets related to LSP not functioning on Mac OS X and Linux.

**Comment by sihammill** [comment]
Fix verified in IDE v2024.800.0.592  Runtime v2024.800.0.616
