### ISSUE TITLE
Garbage Collection: [VM] Games can now consume huge amounts of RAM over time, following fix for 5677 in 2024.400

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#6253]
### Description

In Fields of Mistria, in VM builds on current stable (2024.4) and in the Beta (2024.6), we get memory leaks overtime which eventually get to massive proportions. Right now, FoM uses about 3-4gigs of RAM at all times. When we instead compile in the VM, however, we overtime can balloon to ~30gigs of RAM. There is probably no limit.

### Steps To Reproduce

1. Clone the Fields of Mistria Repository.
2. Run `.build.ps1` on Windows, or `.build.sh` on macOS (note: only apple silicon is supported on dev mac builds)
3. Make sure to select the configuration `debug`.
4. Run the game in the IDE using the play button in VM.
5. At title screen, open the debug console by pressing F2, and then type `system mem_dump` and observe the output (it will also print to the console)
6. Press New Game and enter the game.
7. Open the debug console again and type `new_day 28`. This will take you one month into the game. It will take a bit of time.
8. run `system mem_dump` and observe that it has increased a very large amount.
9. Repeat the above on YYC and observe that `system mem_dump` only mildly changes. 

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly), 2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, macOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yymrennie** [comment]
Fixed in 2024.6

**Comment by YYDan** [comment]
As a slight aside, but I wanted to let you know: "system mem_dump" does not come up as a matching function in your autocomplete, does nothing visible and nothing appears to be logged either when Mike and I tried it.

Regardless, with Runtime v2024.600.0.605 on my PC and using VM the game uses approx:
3760MB when idling on the main menu
4960MB idling when the new game has started and the character is in bed
After executing the jump to 28 Days Later, I can see the RAM climb in steps to somewhere around 5200MB
5055MB idling once on day 28
4950-60MB after idling for about 30 seconds or so, which is where it seems to sit thereafter (it does slowly creep up and drop small amounts)

YYC is 
3730
4935
Same climb, but to maybe only 5150
5045
It then drops to a very-comparable 4945-4950 and sit there for a while
However, after a minute it drops a lot more to sit at 4085-90 (again, it does slowly creep up and drop small amounts)

**Comment by YYDan** [comment]
Checked with Mike and that's the expected results, so Verifying.

(We do wonder if VM was left long if it might do the same final drop, but that's not part of this issue anyway - clearly, the RAM is no longer ballooning on VM.)

**Comment by sanbox-irl** [comment]
@YYDan and @yymrennie I am still getting this behavior on VM on runtime 2024.600.0.602. Can I see how you're replicating this? I do not believe you have solved the issue on the current runtime. I have now replicated it on two different windows PCs, so I believe its on your end.

> As a slight aside, but I wanted to let you know: "system mem_dump" does not come up as a matching function in your autocomplete, does nothing visible and nothing appears to be logged either when Mike and I tried it.

apologies, I was on a branch and forgot to notate that. That bugger command is now on main.

I can also talk on Discord for faster communication (my handle is `jack_irl`)

**Comment by sanbox-irl** [comment]
To emphasize, here are the logs:

```
# this is hanging out in the house, before doing anything...
allocated 3.45gb (free: 3.12gb)

[E0 | 6:55am] TRACE gml_Script_end_day:3 -- Ending spring 1...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 2)...(and it took 2.19s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 2...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 3)...(and it took 2.23s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 3...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 4)...(and it took 2.37s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 4...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 5)...(and it took 2.25s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 5...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 6)...(and it took 2.19s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 6...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 7)...(and it took 2.22s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 7...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 8)...(and it took 2.27s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 8...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 9)...(and it took 2.22s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 9...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 10)...(and it took 2.28s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 10...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 11)...(and it took 2.42s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 11...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 12)...(and it took 2.61s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 12...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 13)...(and it took 7.29s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 13...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 14)...(and it took 6.49s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 14...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 15)...(and it took 2.92s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 15...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 16)...(and it took 2.43s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 16...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 17)...(and it took 2.78s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 17...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 18)...(and it took 4.79s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 18...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 19)...(and it took 2.42s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 19...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 20)...(and it took 2.45s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 20...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 21)...(and it took 2.41s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 21...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 22)...(and it took 2.49s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 22...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 23)...(and it took 2.49s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 23...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 24)...(and it took 2.43s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 24...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 25)...(and it took 2.39s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 25...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 26)...(and it took 2.64s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 26...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 27)...(and it took 2.51s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 27...
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (spring 28)...(and it took 2.47s to get there)
[E0 | 6:00am] TRACE gml_Script_end_day:3 -- Ending spring 28...
[E0 | 6:00am] TRACE gml_Script_spawn_new_season_colliders:180 -- GrowBack spawned in 60 colliders
[E0 | 6:00am] TRACE gml_Script_new_season:73 -- Progressed to summer (and it took 1.74s to get there)
[E0 | 6:00am] TRACE gml_Script_new_day:10 -- it's a brand new day (summer 1)...(and it took 4.42s to get there)

# and now...
[28 | 7:10am] INFO gml_Script_echo@BuggerMenu@BuggerMenu:113 -- allocated 13.23gb (free: 9.07gb)
```

Using the available info on user resources, we aren't seeing any big increase in the amount of user controlled memory:
```
BEFORE NEW_DAY 28: surfaceCount : 10, instanceCount : 24
AFTER NEW_DAY 28: surfaceCount : 08, instanceCount : 23
```
all other user mapped resources are the same count.

That being said, perhaps we are making memory which can't be cleared in some way? I'm not sure. But certainly I am still getting this memory issue!

**Comment by YYDan** [comment]
Hi - I'm not using runtime 602. I'm using a newer internal 605, so that's how I see a change ;)

**Comment by sanbox-irl** [comment]
ah understood, thank you!
