### ISSUE TITLE
@desc and @description not working in 2024.6

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6298]
### Description
I just checked and they do work in 2024.4.1, but not in beta. This applies to both CE1 and CE2.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/e6f96c4c-8f8a-42fd-ad93-9ac607a2223d)

Exact same project in 2024.4 for comparison:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/9dcd767d-8550-4abb-96ad-27f0d78db049)

### Steps To Reproduce
Add `/// @description some event title` or `/// @desc some other event title` to an object's event. The description will not show up in the event list.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[48d74cbc-8381-4952-8dba-3285f23f6f9f](https://api.gamemaker.io/api/github/downloads/48d74cbc-8381-4952-8dba-3285f23f6f9f)

**Comment by yyalansavage** [comment]
Fixed for CE1 (note for me the description appeared on re-opening the events window; but not when creating event /editing description while events window was open). This is not yet implemented for CE2.

**Comment by YYDan** [comment]
Have removed the CE2 mention from the description, as that's not part of this system and therefore not part of this fix either.

(We _should_ have a separate issue for adding support for this into the Inspector already, so that CE2 has a place to put the descriptions. Need to confirm.)

**Comment by caitlinrmcintyre** [comment]
Verified fix for CE1 in Beta IDE v2024.600.0.579  Runtime v2024.600.0.605, thanks.

**Comment by fsdcxq** [comment]
It still appears in IDE v2024.8.0.169, Runtime v2024.8.0.216

**Comment by fsdcxq** [comment]
I want to correct my comment.
It works for objects, but it doesn't work for timelines. (IDE v2024.8.1.171, Runtime v2024.8.1.218)
![not work for timeline](https://github.com/user-attachments/assets/bd640f22-1001-4b6d-a339-184af705d5ac)

**Comment by KormexGit** [comment]
Might be good to file that as a separate report, since it's happening in a different place
