### ISSUE TITLE
Code Editor 2: Autocompleting #macro, #region, or #endregion will add an extra #

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7939]
### Description
Autocompleting anything that starts with a # will add a 2nd # at the start of it

https://github.com/user-attachments/assets/6c2998f3-5f6b-4c2f-a94f-5eb0b8e1d5cc

### Steps To Reproduce
Type # and then autocomplete any of the options offered

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e6d2b1cc-7bdb-4ca4-aa04-375f0494460b](https://api.gamemaker.io/api/github/downloads/e6d2b1cc-7bdb-4ca4-aa04-375f0494460b)

**Comment by zreedy** [comment]
Fixed. Additional changes to how the code completion list sorts snippets so that it orders it as `#macro`, `#region`, `#endregion` which is the most->least common matches. Additionally, `#region` is a snippet which completes the `#endregion` with a description.

**Comment by Emc1923** [comment]
Now when typing just a # the code completion displaying the options available does not appear, only after typing `#m` `#r` `#e`

https://github.com/user-attachments/assets/213e8bf4-7cad-4a1f-99d4-4816d4417984

**Comment by zreedy** [comment]
Unable to reproduce. Closing as fixed.

**Comment by Emc1923** [comment]
Still happening as  IDE v2024.1300.0.727  Runtime v2024.1300.0.739, typing `#` doesn't show any entries until typing `#m`  `#r` or `#e`

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1300.0.727  Runtime v2024.1300.0.739.
