### ISSUE TITLE
 In-Game: function declaration is broken in object inheritance in Nov beta runtime

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#8129]
### Description
The sample project has a parent object with the creation event:
```gml
function setup_from_item_id(){
	init_instance_variables();
}

function init_instance_variables(){}
```
The child object overrides `init_instance_variables` and calls `setup_from_item_id`:

```gml
event_inherited();

function init_instance_variables(){
	obj_var = "hello";
}

setup_from_item_id();
show_debug_message(obj_var);
```

In August runtime, `setup_from_item_id` is able to call the child's overwritten `init_instance_variables`, whereas in Nov runtime, it calls the parent's  `init_instance_variables` instead.

### Steps To Reproduce
1. Run the sample in August runtime for windows vm, see no issue
2. Run in Nov runtime and see crash

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.651 Runtime v2024.1100.0.677

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[f37f3d0a-3927-414b-9da4-ee8b336cbb85](https://api.gamemaker.io/api/github/downloads/f37f3d0a-3927-414b-9da4-ee8b336cbb85)

**Comment by rwkay** [comment]
Fixed in 2024.11

**** IMPORTANT ****

Most of this feature has been backed out from 2024.11 as we have discovered - functions that are declared within an event will still be available through the `asset_` functions, but the optimisation that meant they were called directly (like a function) which would speed up execution as this only worked in cases where object inheritance had been used, and the method for the function was being relied upon.

This was incompatible with the optimisation and so reluctantly we have removed this - we will revisit how this works in GMRT and look to improve the performance of these types of function calls at that point.

**** IMPORTANT ****

**Comment by shichen85** [comment]
I see that this issue's initial beta is listed as `2024.1100.0.686` at https://github.com/orgs/YoYoGames/projects/17/views/37?filterQuery=milestone%3A%222024.11%22+inheritance+, but I just tested the replication sample on that runtime and the issue is still present.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.661  Runtime v2024.1100.0.687

The attached sample no longer crashes.


If you are seeing another issue please file a new report with an attached project that shows the issue. As Russell states, we have mostly backed out a change that was causing this particular issue.

**Comment by shichen85** [comment]
Apologies. Our test case was not set up correctly.
