### ISSUE TITLE
In-Game: [Ubuntu] 202.1300 RT 743 enumerates mice as gamepads

### ISSUE THREAD

**Issue by Lukanibal** [YoYoGames/GameMaker-Bugs#9250]
### Description
I tested the previous runtime, and this doesn't happen, I have included a blank project you can build to see the issue, as well as a screen shot of what's happening on my end.

I can address this in my input code, but it did break my system because it was detecting several gamepads that don't exist.
https://imgur.com/v8LS3UE

Update to include GUID:
`New gamepad = "Razer Razer Basilisk Essential", GUID="03000000321500006500000011010000", buttons = 163, axes = 0, hats = 0`  

Switching back to runtime v2024.1300.0.733 this stops happening.

### Steps To Reproduce
Build game for linux, either GMS2 or GMRT, both do it.
See output.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1300.0.732 Runtime v2024.1300.0.743

### Which operating system(s) are you seeing the problem on?
Linux Linux Mint 21.3 kernel 6.8.0.52

[2d629ca4-c3ae-47e1-b15d-089b54b72407](https://api.gamemaker.io/api/github/downloads/2d629ca4-c3ae-47e1-b15d-089b54b72407)

**Comment by Lukanibal** [comment]
This still happens, I have switched entirely over to Juju and Alynne's Input library and my Razer Basilisk is still detected as a gamepad instead of a mouse.  
This breaks every single project as it's only detecting mouse input if I am pressing keys on the keyboard now...

**Comment by rwkay** [comment]
Fixed in 2024.13 - I have changed the criteria so that at least a single axis is required for a gamepad - we need to recheck the atari classic gamepad works with this fix in place @cameron-home

**Comment by cameron-home** [comment]
Reopening as while mice are no longer being detected as gamepads in IDE v2024.13.0.190 Runtime v2024.13.0.238, the Atari classic gamepad is no longer working. The following error is returned for the gamepad:
```
Joystick needs to have at least 1 axis
!!!!!Hmmmm we don't think is a joystick!!!!!
```

**Comment by offalynne** [comment]
> I have switched entirely over to Juju and Alynne's Input library

This is easily fixed in Input in the meantime: add `,32156500` to the first line of the ’blacklist.csv` datafile (begins with `linux,vid+pid,`)

**Comment by offalynne** [comment]
> *I have changed the criteria so that at least a single axis is required for a gamepad* 

I suggest the heuristic check for axis *or* hat, assuming hat shows up correctly for eg. the VCS classic

**Comment by rwkay** [comment]
Possible fix in 2024.14 - I have added a new check that allows joysticks that have both hats and axes...

**Comment by offalynne** [comment]
> _both hats and axes_

@rwkay hoping this indicates either/or, seeing new results from the hid-nintendo kernel driver on LTS where controllers are indeed showing hat but not axis, eg. SNES NSO Controller:

```
Unable to find mapping for device ""
Joystick has button: 0x130
Joystick has button: 0x131
Joystick has button: 0x133
Joystick has button: 0x134
Joystick has button: 0x136
Joystick has button: 0x137
Joystick has button: 0x138
Joystick has button: 0x139
Joystick has button: 0x13a
Joystick has button: 0x13b
Joystick has hat 0
```

**Comment by cameron-home** [comment]
Issue still occurring with the Atari pad; have spoken to @rwkay and now reopening

**Comment by rwkay** [comment]
I have updated the fix again

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1400.0.790  Runtime v2024.1400.0.798

**Comment by Lukanibal** [comment]
Did a run and it actually enumerated both my mouse and drawing tablet as a gamepad.
Output below:
```Entering main loop.
**********************************.
Decoding sndDoor...
Decoding sndExplosionMedium...
Decoding sndExplosionOther...
Decoding sndGoo...
Decoding sndItemGet...
Decoding sndJeeze...
Decoding sndRespawn...
Decoding sndRip...
Decoding sndShadeDie...
Decoding sndSkrantulaDie...
Decoding sndSwing1...
No gamepad mapping found for GUID 03000000bd2800004a09000000010000
Joystick : Re-read Axis 0 (0) val= -32767
Joystick : Re-read Axis 1 (1) val= -32767
Joystick : Re-read Axis 2 (32) val= -32768
No gamepad mapping found for GUID 03000000321500006500000011010000
Joystick : Re-read Axis 0 (40) val= -32768
No gamepad mapping found for GUID 03000000bd2800004a09000000010000
Joystick : Re-read Axis 0 (0) val= -32767
Joystick : Re-read Axis 1 (1) val= -32767
Joystick : Re-read Axis 2 (32) val= -32768
Joystick : Re-read Axis 3 (55) val= -32768
Joystick : Re-read Axis 4 (61) val= -32767
Joystick : Re-read Axis 5 (62) val= -32767
Decoding sndThrow...
Data too large and INCR mechanism not implemented
Audio group 2 -> Loaded
Input: Gamepad 5 connected
Input: New gamepad = "HANVON UGEE Artist 12 (2nd Gen) Mouse", GUID="03000000bd2800004a09000000010000", buttons = 6, axes = 3, hats = 0
Input: Warning! No SDL definition found for 03000000bd2800004a09000000010000 (vendor=bd28, product=4a09)
Input: Warning! VID+PID "bd284a09" not found in raw type database. Guessing controller type based on description = "HANVON UGEE Artist 12 (2nd Gen) Mouse"
Input: No SDL2 remapping available, falling back to GameMaker's mapping (no mapping)
Input: Gamepad 5 discovered, type = "unknown" (Unknown, guessed=1), description = "HANVON UGEE Artist 12 (2nd Gen) Mouse" (vendor=bd28, product=4a09)
Input: Gamepad 22 connected
Input: New gamepad = "Razer Razer Basilisk Essential", GUID="03000000321500006500000011010000", buttons = 9, axes = 1, hats = 0
Input: Warning! No SDL definition found for 03000000321500006500000011010000 (vendor=3215, product=6500)
Input: Warning! VID+PID "32156500" not found in raw type database. Guessing controller type based on description = "Razer Razer Basilisk Essential"
Input: No SDL2 remapping available, falling back to GameMaker's mapping (no mapping)
Input: Gamepad 22 discovered, type = "unknown" (Unknown, guessed=1), description = "Razer Razer Basilisk Essential" (vendor=3215, product=6500)
Input: Gamepad 26 connected
Input: New gamepad = "HANVON UGEE Artist 12 (2nd Gen)", GUID="03000000bd2800004a09000000010000", buttons = 2, axes = 8, hats = 0
Input: Warning! No SDL definition found for 03000000bd2800004a09000000010000 (vendor=bd28, product=4a09)
Input: Warning! VID+PID "bd284a09" not found in raw type database. Guessing controller type based on description = "HANVON UGEE Artist 12 (2nd Gen)"
Input: No SDL2 remapping available, falling back to GameMaker's mapping (no mapping)
Input: Gamepad 26 discovered, type = "unknown" (Unknown, guessed=1), description = "HANVON UGEE Artist 12 (2nd Gen)" (vendor=bd28, product=4a09)
```
The drawing tablet is not as big a deal as I can just unplug it, but the mouse is kind of important, lol.

**Comment by rwkay** [comment]
I have added a new filter in there for 2024.14 next Beta - lets see what this does @cameron-home we need to check this with the Atari Joystick to ensure it works as well as filtering out the mouse above.
