### ISSUE TITLE
In-Game: [iOS] Crash when closing a game which uses Time Sources in a Clean Up event

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#9604]
### Description

Run the Demoproject on an IPhone and close the app after ~ 3sec.
During the close process the app crashes. It seems like the TimeSource gets freed and every TimeSource operation (in CleanUp) silently crashes.

Demo Project: https://api.gamemaker.io/api/github/downloads/f3a50c95-cfbf-4470-96e4-d7bd9afffe58
Phone: IPhone 7
Version IOS: 14.5

But this crash also happens to other IPhones (For my production games I have like 1000 crashes)

This crash did not happen with 2023.11. But After I have updated GMS from v2023.11 -> GMS v2024.8.1 last year I started to get these timesource bugs for iOS.

### Expected Change

Fix the timesource crash

### Steps To Reproduce

1. Start GameMaker
2. Run Project on iOS
3. wait 3sec
4. close app
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.11.0 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by Glim888** [comment]
I use 

![Image](https://github.com/user-attachments/assets/599ec666-5779-4f0b-bf41-a44c7f9d5b9e)

**Comment by Glim888** [comment]
I tested it again and it does crash with this version.

**Comment by Glim888** [comment]
@stuckie

**Comment by toby-yoyo** [comment]
Fixed an issue in the runtime caused by the non-guaranteed destruction order of static objects when the app is forcefully terminated.

**Comment by YYDan** [comment]
Note that this one did not actually make it into 2024.1300 Beta 6, but happened to be closed during the date range shown in the Beta 6 release notes, so appears in the changelist - it will be in Beta 7.

**Comment by Glim888** [comment]
Yes I will test it today or tomorrow.

**Comment by Glim888** [comment]
Crash is still occurring:

![Image](https://github.com/user-attachments/assets/55ff8101-6814-4a82-bd67-321adc83461f)

![Image](https://github.com/user-attachments/assets/3ef00cce-3a2f-4588-836a-2fdd07e29993)

IPhone 7 Model Number: MN912ZD/A

And here some stacktraces of the timesource-crash, that my players get:

![Image](https://github.com/user-attachments/assets/57f16435-e2b1-44c0-90e5-811afdca3b73)

**Comment by toby-yoyo** [comment]
@Glim888 While your IDE (785) is from beta 8, your runtime (781) is still from beta 6. This first runtime built after the fix was merged was 782 and so it only first appeared in beta 7. If you could update your runtime and retry that would be very much appreciated.

Re-closing for now.

**Comment by Glim888** [comment]
Should I install this one? 

![Image](https://github.com/user-attachments/assets/366b2874-cee7-43b9-b69c-11a932382667)

**Comment by toby-yoyo** [comment]
![Image](https://github.com/user-attachments/assets/ce63e277-b04a-44a4-8288-699e906c6dab)
790 is the runtime paired with your IDE, so that would be best.

**Comment by alicemoretti** [comment]
The latest Runtime is 2024.1300.0.790. You can install that from Preferences > Runtime Feeds > Master > Double click on the runtime 

![Image](https://github.com/user-attachments/assets/c64561bb-abb6-4f61-80a9-a0b0ccd8c80d)

**Comment by Glim888** [comment]
Why cant I see this runtime?

![Image](https://github.com/user-attachments/assets/782ca0d9-21eb-4836-8706-4908ed2cef14)

**Comment by alicemoretti** [comment]
Could you please try the following to fix the missing runtime: 
Make sure you are connected to the internet first and that your AV is not blocking any of GameMaker's processes. 

1- Click on the update button on the runtime feed - Master window (circling arrows above "Status")
2- Click on Restore defaults on the runtime feed - Master window (only restores that window)
3- Relaunch the IDE
4- Sign out and in again of the IDE

**Comment by Glim888** [comment]
Still no new version.

But the .786 should have the fix in it, right? So I can use this version to test.?

**Comment by alicemoretti** [comment]
yes, 786 should also have the fix so you can use that one to test

**Comment by Glim888** [comment]
It still crashes, even with 786

**Comment by Glim888** [comment]
I get now following crash on startup. (For every project)

![Image](https://github.com/user-attachments/assets/ae09088f-84f0-4cae-baa7-3ebbf5a5d950)

![Image](https://github.com/user-attachments/assets/1a858ad7-b4b9-40a6-ac74-482f4f685e6b)

**Comment by toby-yoyo** [comment]
That is a separate issue to this one, so please submit a new bug report for it.

**Comment by Glim888** [comment]
I have tried to add the time_source_destroy() to the delete event instead of the cleanup event. And this works.

Just in case someone need also a workaround until 2024.14 arrives.

**Comment by alicemoretti** [comment]
Closing as verified as per comments. Thank you.
