### ISSUE TITLE
Code Editor 2: Declaration Navigation not working

### ISSUE THREAD

**Issue by MangoB1** [YoYoGames/GameMaker-Bugs#9804]
### Description
CE2 doesn't do anything when I click any declarations in the navigation menu.

### Steps To Reproduce
1. Open Gamemaker
2. Open a gameobject
3. click a declaration
4. See issue

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1300.0.775 Runtime v2024.1300.0.781

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

[1c180db5-6035-4e89-8517-87d03a41b983](https://api.gamemaker.io/api/github/downloads/1c180db5-6035-4e89-8517-87d03a41b983)

**Comment by zreedy** [comment]
Unable to reproduce "nothing happening", clicking through does seem to select variables. Please specify a specific object and variable that's failing for further testing.

I was able to reproduce https://github.com/YoYoGames/GameMaker-Bugs/issues/9805 in this project, which is now fixed. Additionally, the variable `ts` declared in a macro shows up in the declaration list and clicking it selects the line the macro is on. I would consider this to be valid behavior as the variable is declared on this line, it's simply hidden behind the macro.

**Comment by MangoB1** [comment]
The issue was still happening when I just tried it in my existing project on two seperate objects and I recorded a video below but after restarting GameMaker the navigation started working again. 

I am unsure how to reproduce reliably at this point. Will provide updates when possible.

https://github.com/user-attachments/assets/c2ccbba2-5ae8-4d99-8998-fe1f15063e4d

**Comment by MangoB1** [comment]
Hi, the issue still persists for my object obj_game. Has this been resolved or should this issue be reopened? See my comment above thanks.

**Comment by scott-dunbar** [comment]
Issue does not repro following steps in  IDE v2024.1400.0.790  Runtime v2024.1400.0.798

https://github.com/user-attachments/assets/e3c15426-7780-43e0-8148-0522804deef0

**Comment by MangoB1** [comment]
Thanks for looking into it. I'll keep an eye on it and see if it occurs in the next beta.
